package loader;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

public class LoadDataSQL {
	private final static String name = "postgres";
	private final static String password = "postgres";
	private final static String url = "jdbc:postgresql://localhost/is_database";

	public static void main(String[] args) throws SQLException {
		Connection conn = (Connection) DriverManager.getConnection(url, name, password);
		Statement stmt = (Statement) conn.createStatement();
		// Create tables. Works if ran twice
		String sql;
		sql = "CREATE TABLE IF NOT EXISTS researchers (\r\n" + "	name		 TEXT,\r\n"
				+ "	numberofpublications INTEGER,\r\n" + "	reads		 INTEGER,\r\n"
				+ "	citations		 INTEGER,\r\n" + "	institutions_name	 TEXT NOT NULL,\r\n"
				+ "	PRIMARY KEY(name)\r\n" + ");\r\n" + "\r\n" + "CREATE TABLE IF NOT EXISTS skillsandexpertise (\r\n"
				+ "	skill TEXT,\r\n" + "	PRIMARY KEY(skill)\r\n" + ");\r\n" + "\r\n"
				+ "CREATE TABLE IF NOT EXISTS publications (\r\n" + "	id		 INTEGER,\r\n"
				+ "	title		 TEXT,\r\n" + "	datepublication DATE,\r\n" + "	doi		 TEXT,\r\n"
				+ "	source		 TEXT,\r\n" + "	project	 TEXT,\r\n" + "	abstract2	 TEXT,\r\n" + "	PRIMARY KEY(id)\r\n"
				+ ");\r\n" + "\r\n" + "CREATE TABLE IF NOT EXISTS institutions (\r\n" + "	name	 TEXT,\r\n"
				+ "	location	 TEXT,\r\n" + "	department TEXT,\r\n" + "	PRIMARY KEY(name)\r\n" + ");\r\n" + "\r\n"
				+ "CREATE TABLE IF NOT EXISTS researchers_publications (\r\n" + "	researchers_name TEXT,\r\n"
				+ "	publications_id	 INTEGER,\r\n" + "	PRIMARY KEY(researchers_name,publications_id)\r\n" + ");\r\n"
				+ "\r\n" + "CREATE TABLE IF NOT EXISTS researchers_skillsandexpertise (\r\n"
				+ "	researchers_name	 TEXT,\r\n" + "	skillsandexpertise_skill TEXT,\r\n"
				+ "	PRIMARY KEY(researchers_name,skillsandexpertise_skill)\r\n" + ");\r\n" + "\r\n"
				+ "ALTER TABLE researchers DROP CONSTRAINT IF EXISTS researchers_fk1;\r\n"
				+ "ALTER TABLE researchers ADD CONSTRAINT researchers_fk1 FOREIGN KEY (institutions_name) REFERENCES institutions(name);\r\n"
				+ "\r\n"
				+ "ALTER TABLE researchers_publications DROP CONSTRAINT IF EXISTS researchers_publications_fk1;\r\n"
				+ "ALTER TABLE researchers_publications ADD CONSTRAINT researchers_publications_fk1 FOREIGN KEY (researchers_name) REFERENCES researchers(name);\r\n"
				+ "\r\n"
				+ "ALTER TABLE researchers_publications DROP CONSTRAINT IF EXISTS researchers_publications_fk2;\r\n"
				+ "ALTER TABLE researchers_publications ADD CONSTRAINT researchers_publications_fk2 FOREIGN KEY (publications_id) REFERENCES publications(id);\r\n"
				+ "\r\n"
				+ "ALTER TABLE researchers_skillsandexpertise DROP CONSTRAINT IF EXISTS researchers_skillsandexpertise_fk1;\r\n"
				+ "ALTER TABLE researchers_skillsandexpertise ADD CONSTRAINT researchers_skillsandexpertise_fk1 FOREIGN KEY (researchers_name) REFERENCES researchers(name);\r\n"
				+ "\r\n"
				+ "ALTER TABLE researchers_skillsandexpertise DROP CONSTRAINT IF EXISTS researchers_skillsandexpertise_fk2;\r\n"
				+ "ALTER TABLE researchers_skillsandexpertise ADD CONSTRAINT researchers_skillsandexpertise_fk2 FOREIGN KEY (skillsandexpertise_skill) REFERENCES skillsandexpertise(skill);\r\n"
				+ "\r\n" + "";
		stmt.executeUpdate(sql);

		// Add institutions, works if run twice
		sql = "INSERT into institutions (name, location, department)\r\n"
				+ "Values ('Federal University Otuoke', 'Bayelsa-Nigeria', 'Biochemistry'), ('University of Technology Sydney', 'Sydney, NSW, Australia', 'UTS · Advanced Analytics Institute (AAI)'), ('LUISS Guido Carli, Libera Università Internazionale degli Studi Sociali','Rome, Italy','Luiss · Department of Business and Management') ON CONFLICT DO NOTHING;";
		stmt.executeUpdate(sql);

		// Add researchers, works if run twice
		sql = "Insert into researchers (name, numberofpublications, reads, citations, institutions_name)\r\n"
				+ "Values ('Joel Johnson', 19, 270, 82, 'Federal University Otuoke'), ('Shoujin Wang', 32, 6930, 272, 'University of Technology Sydney'), ('Liang Hu', 36, 4091, 419, 'University of Technology Sydney'), ('Longbing Cao', 351, 53222, 5218, 'University of Technology Sydney'), ('Federica Brunetta', 54, 8059, 86, 'LUISS Guido Carli, Libera Università Internazionale degli Studi Sociali') ON CONFLICT DO NOTHING;";
		stmt.executeUpdate(sql);

		// Add skills and expertise, works if run twice
		sql = "Insert into skillsandexpertise (skill)\r\n"
				+ "Values ('Proteins'), ('Chromatography'), ('Protein Purification'), ('Enzymes'), ('Enzyme Activity'), ('Protein Characterization'), ('Protein Biochemistry'), ('Protein Expression'), ('Protein Structure'), ('Biochemistry'), ('Information and Communication Technology'), ('Information Technology'), ('Recommender Systems'), ('Information System Management'), ('Information Management'), ('Algorithms'), ('Machine Learning'), ('Data Mining and Knowledge Discovery'), ('Computational Intelligence'), ('Data Mining'), ('Artificial Intelligence'), ('Association Rule Mining'), ('Clustering'), ('Classification'), ('Mining'), ('Pattern Recognition'), ('Network'), ('Outsourcing'), ('Microsoft Windows'), ('Environment'), ('Entrepreneurship'), ('Institutions'), ('Corporate Strategy') ON CONFLICT DO NOTHING;";
		stmt.executeUpdate(sql);

		// Add researchers and skills connection, works if run twice
		sql = "Insert into researchers_skillsandexpertise (researchers_name, skillsandexpertise_skill)\r\n"
				+ "Values ('Joel Johnson', 'Proteins'), ('Joel Johnson', 'Chromatography'), ('Joel Johnson', 'Protein Purification'), ('Joel Johnson', 'Enzymes'), ('Joel Johnson', 'Enzyme Activity'), ('Joel Johnson', 'Protein Characterization'), ('Joel Johnson', 'Protein Biochemistry'), ('Joel Johnson', 'Protein Expression'), ('Joel Johnson', 'Protein Structure'), ('Joel Johnson', 'Biochemistry'), ('Shoujin Wang', 'Information and Communication Technology'), ('Shoujin Wang', 'Information Technology'), ('Shoujin Wang', 'Recommender Systems'), ('Shoujin Wang', 'Information System Management'), ('Shoujin Wang', 'Information Management'), ('Shoujin Wang', 'Algorithms'), ('Liang Hu', 'Recommender Systems'), ('Liang Hu', 'Machine Learning'), ('Liang Hu', 'Data Mining and Knowledge Discovery'), ('Longbing Cao', 'Computational Intelligence'), ('Longbing Cao', 'Data Mining'), ('Longbing Cao', 'Artificial Intelligence'), ('Longbing Cao', 'Algorithms'), ('Longbing Cao', 'Association Rule Mining'), ('Longbing Cao', 'Clustering'), ('Longbing Cao', 'Classification'), ('Longbing Cao', 'Mining'), ('Longbing Cao', 'Machine Learning'), ('Longbing Cao', 'Pattern Recognition'), ('Federica Brunetta', 'Network'), ('Federica Brunetta', 'Outsourcing'), ('Federica Brunetta', 'Microsoft Windows'), ('Federica Brunetta', 'Environment'), ('Federica Brunetta', 'Entrepreneurship'), ('Federica Brunetta', 'Institutions'), ('Federica Brunetta', 'Corporate Strategy') ON CONFLICT DO NOTHING;";
		stmt.executeUpdate(sql);

		// Add publications 1, works if run twice
		sql = "INSERT into publications (id, title, datepublication, doi, source, project, abstract2) VALUES\r\n"
				+ "(1, 'Changes in Haematological Parameters Following the Administration of Crude Extract from Tympanotonus fuscatus (Periwinkle) in Rats', TO_DATE('20140101','YYYYMMDD'), '', 'Australian Journal of Basic and Applied Sciences', 'Changes in haematogical parameters following the administration of crude extract from Tympanotonus fuscatus (Periwinkle) in rats', 'Background:  The  consumption  of  Periwinkle  (Tympanotonus  fuscatus)  in  various meals in Nigeria is on the increase. It is important to ascertain the effects of the various components of our  everyday meal  on the  body functions. Objective: This study was embarked  upon  to  investigate  the  effect  of  crude  extract  from  Periwinkle (Tympanotonus  fuscatus)  on  haematological  parameters.  Results:  The  graded concentrations of the extract (2.82 - 180.48mgProtein/kg) were administered i.p. to the rats to determine the LD50 value of the extract as preliminary studies. Eighteen albino wistar rats  weighing 180  - 240  g were randomly assigned into 3 groups (n = 6), thus; control, low (7mgProtein/ml) and high (52mgProtein/ml) doses extract treated groups. All animals had free access to drinking water and  normal rat feed for 6 weeks.  The result showed  that the extract had a protein content of 10.12 ±  0.00mgProtein/ml and LD50 values of 61.48mgProtein/ml. Both the low and high doses produced significant increase in  RBC count  (p<0.001) compared  with control. The extract treated  groups also had significant increase in Hb (p<0.001), PCV (P<0.001), MCH (p<0.001), MCHC (p<0.001) and WBC counts (p<0.001). The results also showed that the extract treated groups  had increased  platelet count  (p<0.001), but  decreased  mean  platelet  volume (p<0.001), platelet distribution width (p<0.001) and platelet large cell ratio (p<0.001). Conclusion: The  edible molluscan  sea food (Periwinkle) probably contains accessory nutrients that enhance blood cells production  and reduction in  platelet indices in  rats. They could therefore serve as alternative source of nutrient'), \r\n"
				+ "(2, 'The effects of oral and intraperitoneal administration of ethanol on the activities of hepatic glucose-6-phosphate and 6-phosphogluconate dehydrogenases in rats', TO_DATE('19880301','YYYYMMDD'), '10.1016/0741-8329(88)90007-9', 'PubMed', 'Changes in haematogical parameters following the administration of crude extract from Tympanotonus fuscatus (Periwinkle) in rats', 'The activities of hepatic glucose-6-phosphate and 6-phosphogluconate dehydrogenases decreased significantly only in male rats, when rats of both sexes were fed a 2% sucrose solution containing 25% ethanol for six weeks. Sucrose (2%) activation of these enzymes was significant only in female rats. The daily administration of ethanol (5 g/kg body wt.) by intraperitoneal injection for two weeks significantly decreased the activities of these enzymes and eliminated the sex differences in the response to ethanol ingestion.'),\r\n"
				+ "(3, 'Immobilization of chicken liver fructose 1,6-bisphosphatase on CNBr-activated Sepharose', TO_DATE('19851001','YYYYMMDD'), '10.1007/BF01951702', 'PubMed', '', 'Chicken liver fructose 1,6-bisphosphatase is readily immobilized on CNBr-activated Sepharose. The immobilization alters some enzymatic properties. They include broader pH activity curve, loss of activation by K+ or NH 4+, increased resistance to inactivation by trypsin, decreased sensitivity to AMP inhibition, and loss of cooperative interaction among AMP-binding sites. The immobilized enzyme retains about 38% or 19% of the specific activity of the native enzyme when the activity is measured in the absence or presence of K+, resepctively.'),\r\n"
				+ "(4, 'Synergistic effect of AMP and fructose 2,6-bisphosphate on the protection of fructose 1,6-bisphosphatase against inactivation by trypsin', TO_DATE('19831201','YYYYMMDD'), '10.1007/BF01990383', 'PubMed', '', 'The rate of inactivation of chicken liver fructose 1,6-bisphosphatase by trypsin is reduced if the digestive reaction is conducted in the presence of AMP or fructose 2,6-bisphosphate. The effects of these 2 compounds are synergistic. Although fructose 1,6-bisphosphate does not protect the enzyme against tryptic inactivation, it can enhance the effect of AMP. Selective modification of the AMP allosteric site of fructose 1,6-bisphosphatase with pyridoxal-P and NaBH4 renders the enzyme more resistant to tryptic inactivation, but the modified enzyme is no longer responsive to the protective effect of AMP.'),\r\n"
				+ "(5, 'Fructose-1,6-bisphosphatase from Turkey liver', TO_DATE('19820201','YYYYMMDD'), '10.1016/S0076-6879(82)90151-3', 'PubMed', '', 'This chapter describes an assay method and the purification procedure for fructose-1,6-bisphosphatase from turkey liver. Turkey liver FBPase can be satisfactorily isolated from freshly removed livers or frozen livers. For the assay of fructose-l,6-bisphosphatase (FBPase), the formation of fructose 6-phosphate is measured spectrophotometrically by following the reduction of NADP at 340 nm in a coupled reaction containing excess of phosphoglucose isomerase and glucose-6-phosphate dehydrogenase. The purification process involves preparation of crude extract, heat treatment, removal of unwanted proteins by phosphocellulose, phosphocellulose absorption and chromatography, and Blue Sepharose chromatography. The molecular weight of the enzyme is approximately 144,000, as calculated by sedimentation analysis in a sucrose density gradient. Without chelating agents, the enzyme has optimum activity at pH 8.4–8.5 and this enzyme requires divalent cations (Mg2+ or Mn2+) for activity. Turkey liver FBPase can be readily immobilized on CNBr-activated Sepharose 4B.') ON CONFLICT DO NOTHING;";
		stmt.executeUpdate(sql);

		// Add publications 2, works if run twice
		sql = "INSERT into publications (id, title, datepublication, doi, source, project, abstract2) VALUES\r\n"
				+ "(6, 'The Era of Intelligent Recommendation: Editorial on Intelligent Recommendation with Advanced AI and Learning', TO_DATE('20201001','YYYYMMDD'), '', 'IEEE Intelligent Systems', 'Session-based Recommender Systems', ''),\r\n"
				+ "(7, 'Double-Wing Mixture of Experts for Streaming Recommendations', TO_DATE('20200901','YYYYMMDD'), '', '', '', 'Streaming Recommender Systems (SRSs) commonly train recommendation models on newly received data only to address user preference drift, i.e., the changing user preferences towards items. However, this practice overlooks the long-term user preferences embedded in historical data. More importantly, the common heterogeneity in data stream greatly reduces the accuracy of streaming recommendations. The reason is that different preferences (or characteristics) of different types of users (or items) cannot be well learned by a unified model. To address these two issues, we propose a Variational and Reservoir-enhanced Sampling based Double-Wing Mixture of Experts framework, called VRS-DWMoE, to improve the accuracy of streaming recommendations. In VRS-DWMoE, we first devise variational and reservoir-enhanced sampling to wisely complement new data with historical data, and thus address the user preference drift issue while capturing long-term user preferences. After that, we propose a Double-Wing Mixture of Experts (DWMoE) model to first effectively learn heterogeneous user preferences and item characteristics, and then make recommendations based on them. Specifically, DWMoE contains two Mixture of Experts (MoE, an effective ensemble learning model) to learn user preferences and item characteristics, respectively. Moreover, the multiple experts in each MoE learn the preferences (or characteristics) of different types of users (or items) where each expert specializes in one underlying type. Extensive experiments demonstrate that VRS-DWMoE consistently outperforms the state-of-the-art SRSs.'),\r\n"
				+ "(8, 'Stratified and Time-aware Sampling based Adaptive Ensemble Learning for Streaming Recommendations', TO_DATE('20200901','YYYYMMDD'), '', '', '', 'Recommender systems have played an increasingly important role in providing users with tailored suggestions based on their preferences. However, the conventional offline recommender systems cannot handle the ubiquitous data stream well. To address this issue, Streaming Recommender Systems (SRSs) have emerged in recent years, which incrementally train recommendation models on newly received data for effective real-time recommendations. Focusing on new data only benefits addressing concept drift, i.e., the changing user preferences towards items. However, it impedes capturing long-term user preferences. In addition, the commonly existing underload and overload problems should be well tackled for higher accuracy of streaming recommendations. To address these problems, we propose a Stratified and Time-aware Sampling based Adaptive Ensemble Learning framework, called STS-AEL, to improve the accuracy of streaming recommendations. In STS-AEL, we first devise stratified and time-aware sampling to extract representative data from both new data and historical data to address concept drift while capturing long-term user preferences. Also, incorporating the historical data benefits utilizing the idle resources in the underload scenario more effectively. After that, we propose adaptive ensemble learning to efficiently process the overloaded data in parallel with multiple individual recommendation models, and then effectively fuse the results of these models with a sequential adaptive mechanism. Extensive experiments conducted on three real-world datasets demonstrate that STS-AEL, in all the cases, significantly outperforms the state-of-the-art SRSs.'),\r\n"
				+ "(9, 'Concept Representation by Learning Explicit and Implicit Concept Couplings', TO_DATE('20200901','YYYYMMDD'), '10.1109/MIS.2020.3021188', 'Intelligent Systems, IEEE', '', E'Generating the precise semantic representation of a word/concept is a fundamental task in natural language processing. Recent studies which incorporate semantic knowledge into word embedding have shown their potential in improving the semantic representation of a concept. However, existing approaches only achieved limited performance improvement as they usually (1) model a word\\'s semantics from some explicit aspects while ignoring the intrinsic aspects of the word, (2) treat semantic knowledge as a supplement of word embeddings, and (3) consider partial relations between concepts while ignoring rich coupling relations between them, such as explicit concept co-occurrences in descriptive texts in a corpus as well as concept hyperlink relations in a knowledge network, and implicit couplings between the explicit relations. In human consciousness, concepts are associated with various coupling relations, which inspires us to capture as many concept couplings as possible for building a better concept representation. We thus propose a neural coupled concept representation (CoupledCR) framework and its instantiation: a coupled concept embedding (CCE) model. CCE first learns two types of explicit couplings from concept cooccurrences and hyperlink relations respectively, and then learns a type of high-level implicit couplings between these two types of explicit couplings. Extensive experimental results on real-world datasets show that CCE significantly outperforms state-of-the-art semantic representation methods.'),\r\n"
				+ "(10, 'Intention2Basket: A Neural Intention-driven Approach for Dynamic Next-basket Planning', TO_DATE('20200701','YYYYMMDD'), '10.24963/ijcai.2020/319', '', 'Session-based Recommender Systems', 'User purchase behaviours are complex and dynamic, which are usually observed as multiple choice actions across a sequence of shopping baskets. Most of the existing next-basket prediction approaches model user actions as homogeneous sequence data without considering complex and heterogeneous user intentions, impeding deep under-standing of user behaviours from the perspective of human inside drivers and thus reducing the prediction performance. Psychological theories have indicated that user actions are essentially driven by certain underlying intentions (e.g., diet and entertainment). Moreover, different intentions may influence each other while different choices usually have different utilities to accomplish an intention. Inspired by such psychological insights, we formalize the next-basket prediction as an Intention Recognition, Modelling and Accomplishing problem and further design the Intention2Basket (Int2Ba in short) model. In Int2Ba, an Intention Recognizer, a Coupled Intention Chain Net, and a Dynamic Basket Planner are specifically designed to respectively recognize, model and accomplish the heterogeneous intentions behind a sequence of baskets to better plan the next-basket. Extensive experiments on real-world datasets show the superiority of Int2Ba over the state-of-the-art approaches.') ON CONFLICT DO NOTHING;";
		stmt.executeUpdate(sql);

		// Add publications 3, works if run twice
		sql = "INSERT into publications (id, title, datepublication, doi, source, project, abstract2) VALUES\r\n"
				+ "(11, 'Jointly Modeling Intra- and Inter-transaction Dependencies with Hierarchical Attentive Transaction Embeddings for Next-item Recommendation', TO_DATE('20200501','YYYYMMDD'), '', '', '', 'A transaction-based recommender system (TBRS) aims to predict the next item by modeling dependencies in transactional data. Generally, two kinds of dependencies considered are intra-transaction dependency and inter-transaction dependency. Most existing TBRSs recommend next item by only modeling the intra-transaction dependency within the current transaction while ignoring inter-transaction dependency with recent transactions that may also affect the next item. However, as not all recent transactions are relevant to the current and next items, the relevant ones should be identified and prioritized. In this paper, we propose a novel hierarchical attentive transaction embedding (HATE) model to tackle these issues. Specifically, a two-level attention mechanism integrates both item embedding and transaction embedding to build an attentive context representation that incorporates both intraand inter-transaction dependencies. With the learned context representation, HATE then recommends the next item. Experimental evaluations on two real-world transaction datasets show that HATE significantly outperforms the state-ofthe-art methods in terms of recommendation accuracy.'),\r\n"
				+ "(12, 'Graph Learning Approaches to Recommender Systems: A Review', TO_DATE('20200401','YYYYMMDD'), '', '', '', E'Recent years have witnessed the fast development of the emerging topic of Graph Learning based Recommender Systems (GLRS). GLRS mainly employ the advanced graph learning approaches to model users\\' preferences and intentions as well as items\\' characteristics and popularity for Recommender Systems (RS). Differently from conventional RS, including content based filtering and collaborative filtering, GLRS are built on simple or complex graphs where various objects, e.g., users, items, and attributes, are explicitly or implicitly connected. With the rapid development of graph learning, exploring and exploiting homogeneous or heterogeneous relations in graphs is a promising direction for building advanced RS. In this paper, we provide a systematic review of GLRS, on how they obtain the knowledge from graphs to improve the accuracy, reliability and explainability for recommendations. First, we characterize and formalize GLRS, and then summarize and categorize the key challenges in this new research area. Then, we survey the most recent and important developments in the area. Finally, we share some new research directions in this vibrant area.'),\r\n"
				+ "(13, 'Representation Learning with Multiple Lipschitz-Constrained Alignments on Partially-Labeled Cross-Domain Data', TO_DATE('20200401','YYYYMMDD'), '10.1609/aaai.v34i04.5856', 'Proceedings of the AAAI Conference on Artificial Intelligence', '', 'The cross-domain representation learning plays an important role in tasks including domain adaptation and transfer learning. However, existing cross-domain representation learning focuses on building one shared space and ignores the unlabeled data in the source domain, which cannot effectively capture the distribution and structure heterogeneities in cross-domain data. To address this challenge, we propose a new cross-domain representation learning approach: MUltiple Lipschitz-constrained AligNments (MULAN) on partially-labeled cross-domain data. MULAN produces two representation spaces: a common representation space to incorporate knowledge from the source domain and a complementary representation space to complement the common representation with target local topological information by Lipschitz-constrained representation transformation. MULAN utilizes both unlabeled and labeled data in the source and target domains to address distribution heterogeneity by Lipschitz-constrained adversarial distribution alignment and structure heterogeneity by cluster assumption-based class alignment while keeping the target local topological information in complementary representation by self alignment. Moreover, MULAN is effectively equipped with a customized learning process and an iterative parameter updating process. MULAN shows its superior performance on partially-labeled semi-supervised domain adaptation and few-shot domain adaptation and outperforms the state-of-the-art visual domain adaptation models by up to 12.1%.') ON CONFLICT DO NOTHING;";
		stmt.executeUpdate(sql);

		// Add publications 4, works if run twice
		sql = "INSERT into publications (id, title, datepublication, doi, source, project, abstract2) VALUES\r\n"
				+ "(14, 'Digitalization in the agri-food industry: the relationship between technology and sustainable development', TO_DATE('20200701','YYYYMMDD'), '10.1108/MD-09-2019-1328', 'Management Decision', '', 'Purpose Digitalization is becoming the subject of considerable interest in the literature. This is in view of its relevance in addressing social problems and contributing to the development of communities and societies. In the agri-food-industry, digitalization is also expected to contribute significantly to solve several challenges the sector is facing at this moment, such as the increasing food demand and resource use. However, the effects of advanced technologies are less a function of the technologies themselves than of how they are used by people. The study analyses the dominant challenges faced by firms in the agri-food industry in the usage and adoption of digital technology. Also, they show how these challenges impact on the sustainable development of digital technology for firms in the industry and provide avenues for future research. Design/methodology/approach The authors propose a structured literature review aiming to investigate the following research question: what are the main challenges faced by firms within the agri-food industry in the adoption of smart technologies? Findings Results illustrate the dominant challenges faced by firms in the agri-food industry in the usage and adoption of digital technology. Also, they show how these challenges impact on the sustainable development of digital technology for firms in the industry and provide avenues for future research. Originality/value So far, in the context of digitalization in the agri-food industry, various researchers have analysed different kinds of challenges to the adoption of smart technologies. This work reviews these contributions to create a clear reference framework of the challenges faced by agri-food firms while providing future avenues of research and implications at a policymaking, economic-managerial and socio-environmental level.'),\r\n"
				+ "(15, 'Corrigendum to “Central positions and performance in the scientific community. Evidences from clinical research projects” [J. Bus. Res. 68(5) (2015) 1074–1081]', TO_DATE('20200701','YYYYMMDD'), '10.1016/j.jbusres.2020.04.032', 'Journal of Business Research', '', ''),\r\n"
				+ "(16, 'Faraway, Not So Close: The Conditions That Hindered Knowledge Sharing and Open Innovation in an Online Business Social Network', TO_DATE('20200601','YYYYMMDD'), '10.1109/TEM.2020.2983369', 'IEEE Transactions on Engineering Management', '', 'This article explains the main mechanisms influencing the knowledge collaboration dynamics occurring across an online business community. Prior research study had conceived firms as autonomous entities competing against each other to reach the competitive advantage. Nonetheless, online business social networks (BSNs) can be seen as networks of organizations that interact within digital structures, providing an optimal locus to foster external knowledge flows, enabling participants to share knowledge across organizational boundaries, and eventually leading to open innovation outcomes. We analyze how virtual networks of business relationships influence the form of knowledge collaboration firms can be engaged in. We analyze the entire three-year collaborative history of a BSN. After a promising launch of the BSN, it declined and failed. By analyzing front- and backstage combined with organizational and technological features of the online business community, we identify and discuss five categories of mechanisms affecting the knowledge collaboration over time and reducing the firms’ uncertainty in exchanging information: first, orchestrators’ skills and competencies in running the online platform; second, internal firm capabilities allocating proper organizational resources; third, usability of the digital platform; four, interconnections between frontstage and backstage combined with technological and organizational features; and fifth, perceived virtual copresence.'),\r\n"
				+ "(17, 'Cognitive biases and decision-making strategies in times of change: a systematic literature review', TO_DATE('20200501','YYYYMMDD'), '10.1108/MD-07-2019-1006', 'Management Decision', '', 'Purpose In a work environment marked by unprecedented complexity, volatility and ambiguity, managers must accomplish their objectives while navigating many challenges. This paper aims to investigate potential interrelations among environmental transformations, cognitive biases and strategic decisions. In particular, the purpose of the study is to crystallize the state of art on the impact of cognitive biases on strategic decisions, in the context of environmental transformations. Design/methodology/approach The authors have conducted a systematic literature review to identify existing relevant work on this topic and to detect potential avenues for future research. Findings The findings highlight how decision-making is influenced and enabled by internal (e.g. perception) and external factors (e.g. digitalization). Specifically, the strategic role of cognitive biases appears to be crucial when investigating the related impact on strategic decisions in times of environmental transformation. Practical implications Implications are drawn for scholars and practitioners interested in evaluating the role of specific decision-making determinants for the formation and implementation of strategic decisions. In this sense, we stress that decision-makers need to manage their cognitive biases and select the right information out of a wide data set in order to adapt to environmental transformations. Originality/value By systematizing the literature review, potential interrelations among environmental transformations, cognitive biases and strategic decisions are identified. Furthermore, the primary phases that drive the decision-making process are proposed (analysis, decision, onboarding and control).'),\r\n"
				+ "(18, E'When birds of a feather don\\'t flock together: Diversity and innovation outcomes in international R&D collaboration.', TO_DATE('20190901','YYYYMMDD'), '10.1016/j.jbusres.2019.08.033', 'Journal of Business Research', '', 'Collaboration is a key to success. Nonetheless, collaboration dynamics are affected by partner compatibility, which, in turn, is strongly affected by team member diversity. Studies on team diversity have shown significant variation in the magnitude, significance, and causal direction of the correlations. We examine how international R&D teams collaborate, investigating the impact of team diversity on innovation. We focus on institutional diversity to analyze how, together with the duration of the collaboration, it affects innovation outcomes. We argue that institutional diversity hampers effective knowledge sharing and negatively affects innovation outcomes. However, this negative effect is mitigated by the duration of the R&D collaboration. The longer the diverse actors collaborate, the more likely they are to overcome the barriers of institutional diversity and find effective modes of collaboration for knowledge transfer and innovation. We test our hypotheses in the context of 3,658 clinical trial projects conducted between 2001 and 2015.') ON CONFLICT DO NOTHING;\r\n"
				+ "";
		stmt.executeUpdate(sql);

		// Add researchers and publications 1, works if run twice
		sql = "INSERT into researchers_publications (researchers_name, publications_id) VALUES\r\n"
				+ "('Joel Johnson', 1), ('Joel Johnson', 2), ('Joel Johnson', 3), ('Joel Johnson', 4), ('Joel Johnson', 5) ON CONFLICT DO NOTHING;";
		stmt.executeUpdate(sql);

		// Add researchers and publications 2, works if run twice
		sql = "INSERT into researchers_publications (researchers_name, publications_id) VALUES\r\n"
				+ "('Shoujin Wang', 6), ('Shoujin Wang', 7), ('Shoujin Wang', 8), ('Shoujin Wang', 9), ('Shoujin Wang', 10), ('Shoujin Wang', 11), ('Shoujin Wang', 12) ON CONFLICT DO NOTHING;";
		stmt.executeUpdate(sql);

		// Add researchers and publications 3, works if run twice
		sql = "INSERT into researchers_publications (researchers_name, publications_id) VALUES\r\n"
				+ "('Liang Hu', 6), ('Liang Hu', 10), ('Liang Hu', 11), ('Liang Hu', 12), ('Liang Hu', 13) ON CONFLICT DO NOTHING;";
		stmt.executeUpdate(sql);

		// Add researchers and publications 4, works if run twice
		sql = "INSERT into researchers_publications (researchers_name, publications_id) VALUES\r\n"
				+ "('Longbing Cao', 6), ('Longbing Cao', 10), ('Longbing Cao', 11), ('Longbing Cao', 12), ('Longbing Cao', 13) ON CONFLICT DO NOTHING;";
		stmt.executeUpdate(sql);

		// Add researchers and publications 5, works if run twice
		sql = "INSERT into researchers_publications (researchers_name, publications_id) VALUES\r\n"
				+ "('Federica Brunetta', 14), ('Federica Brunetta', 15), ('Federica Brunetta', 16), ('Federica Brunetta', 17), ('Federica Brunetta', 18)  ON CONFLICT DO NOTHING;";
		stmt.executeUpdate(sql);

		System.out.println("\nALL DATA LOADED\n");
	}
}